// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"

	models0 "github.com/runatlantis/atlantis/server/jobs/models"
)

func AnyModels0PullContext() models0.PullContext {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(models0.PullContext))(nil)).Elem()))
	var nullValue models0.PullContext
	return nullValue
}

func EqModels0PullContext(value models0.PullContext) models0.PullContext {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue models0.PullContext
	return nullValue
}

func NotEqModels0PullContext(value models0.PullContext) models0.PullContext {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue models0.PullContext
	return nullValue
}

func Models0PullContextThat(matcher pegomock.ArgumentMatcher) models0.PullContext {
	pegomock.RegisterMatcher(matcher)
	var nullValue models0.PullContext
	return nullValue
}
