// Code generated by pegomock. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/handlers (interfaces: ProjectJobUrlGenerator)

package mocks

import (
	pegomock "github.com/petergtz/pegomock"
	models "github.com/runatlantis/atlantis/server/events/models"
	"reflect"
	"time"
)

type MockProjectJobUrlGenerator struct {
	fail func(message string, callerSkip ...int)
}

func NewMockProjectJobUrlGenerator(options ...pegomock.Option) *MockProjectJobUrlGenerator {
	mock := &MockProjectJobUrlGenerator{}
	for _, option := range options {
		option.Apply(mock)
	}
	return mock
}

func (mock *MockProjectJobUrlGenerator) SetFailHandler(fh pegomock.FailHandler) { mock.fail = fh }
func (mock *MockProjectJobUrlGenerator) FailHandler() pegomock.FailHandler      { return mock.fail }

func (mock *MockProjectJobUrlGenerator) GenerateProjectJobUrl(p models.ProjectCommandContext) string {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockProjectJobUrlGenerator().")
	}
	params := []pegomock.Param{p}
	result := pegomock.GetGenericMockFrom(mock).Invoke("GenerateProjectJobUrl", params, []reflect.Type{reflect.TypeOf((*string)(nil)).Elem()})
	var ret0 string
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(string)
		}
	}
	return ret0
}

func (mock *MockProjectJobUrlGenerator) VerifyWasCalledOnce() *VerifierMockProjectJobUrlGenerator {
	return &VerifierMockProjectJobUrlGenerator{
		mock:                   mock,
		invocationCountMatcher: pegomock.Times(1),
	}
}

func (mock *MockProjectJobUrlGenerator) VerifyWasCalled(invocationCountMatcher pegomock.Matcher) *VerifierMockProjectJobUrlGenerator {
	return &VerifierMockProjectJobUrlGenerator{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
	}
}

func (mock *MockProjectJobUrlGenerator) VerifyWasCalledInOrder(invocationCountMatcher pegomock.Matcher, inOrderContext *pegomock.InOrderContext) *VerifierMockProjectJobUrlGenerator {
	return &VerifierMockProjectJobUrlGenerator{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		inOrderContext:         inOrderContext,
	}
}

func (mock *MockProjectJobUrlGenerator) VerifyWasCalledEventually(invocationCountMatcher pegomock.Matcher, timeout time.Duration) *VerifierMockProjectJobUrlGenerator {
	return &VerifierMockProjectJobUrlGenerator{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		timeout:                timeout,
	}
}

type VerifierMockProjectJobUrlGenerator struct {
	mock                   *MockProjectJobUrlGenerator
	invocationCountMatcher pegomock.Matcher
	inOrderContext         *pegomock.InOrderContext
	timeout                time.Duration
}

func (verifier *VerifierMockProjectJobUrlGenerator) GenerateProjectJobUrl(p models.ProjectCommandContext) *MockProjectJobUrlGenerator_GenerateProjectJobUrl_OngoingVerification {
	params := []pegomock.Param{p}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "GenerateProjectJobUrl", params, verifier.timeout)
	return &MockProjectJobUrlGenerator_GenerateProjectJobUrl_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockProjectJobUrlGenerator_GenerateProjectJobUrl_OngoingVerification struct {
	mock              *MockProjectJobUrlGenerator
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockProjectJobUrlGenerator_GenerateProjectJobUrl_OngoingVerification) GetCapturedArguments() models.ProjectCommandContext {
	p := c.GetAllCapturedArguments()
	return p[len(p)-1]
}

func (c *MockProjectJobUrlGenerator_GenerateProjectJobUrl_OngoingVerification) GetAllCapturedArguments() (_param0 []models.ProjectCommandContext) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]models.ProjectCommandContext, len(c.methodInvocations))
		for u, param := range params[0] {
			_param0[u] = param.(models.ProjectCommandContext)
		}
	}
	return
}
