// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	locking "github.com/runatlantis/atlantis/server/events/locking"
)

func AnyLockingApplyCommandLockResponse() locking.ApplyCommandLockResponse {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(locking.ApplyCommandLockResponse))(nil)).Elem()))
	var nullValue locking.ApplyCommandLockResponse
	return nullValue
}

func EqLockingApplyCommandLockResponse(value locking.ApplyCommandLockResponse) locking.ApplyCommandLockResponse {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue locking.ApplyCommandLockResponse
	return nullValue
}
