linters:
  enable:
    - errcheck
    - gochecknoinits
    # We don't use goconst because it gives false positives in the tests.
    #  - goconst
    - gofmt
    - revive
    - gosec
    - gosimple
    - ineffassign
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - vet
    - vetshadow
    - dogsled
    - dupword
    - unparam
    - interfacebloat
    - usestdlibvars
    - whitespace
issues:
  exclude-rules:
    - path: server/legacy/controllers/events/events_controller(.+)test.go
      linters:
        - dogsled
    - path: server/legacy/events/event_parser_test.go
      linters:
        - dogsled
    - path: server/legacy/events/command_runner_test.go
      linters:
        - dogsled
linters-settings:
  interfacebloat:
    max: 6
