version: "2"
linters:
  enable:
    - dogsled
    - dupword
    - gochecknoinits
    - gosec
    - interfacebloat
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
  settings:
    interfacebloat:
      max: 7
    staticcheck:
      checks:
        - all
        - -QF1001
        - -QF1007
        - -QF1008
        - -QF1011
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
        - -ST1023
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dogsled
        path: server/legacy/controllers/events/events_controller(.+)test.go
      - linters:
          - dogsled
        path: server/legacy/events/event_parser_test.go
      - linters:
          - dogsled
        path: server/legacy/events/command_runner_test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
