repos:
  - id: {{ .Env.ALLOWED_REPOS }} 
    apply_requirements: []
    checkout_strategy: merge

temporal:
  host: temporalite
  port: 7233

policies:
  # change this to the name of your github organization
  organization: <FILL THIS IN>
  conftest_version: "0.25.0"
