repos:
  - id: {{ .Env.ALLOWED_REPOS }} 
    apply_requirements: []
    checkout_strategy: merge

metrics:
  statsd:
    host: "127.0.0.1"
    port: "8125"

temporal:
  host: temporalite
  port: 7233
