repos:
  - id: {{ .Env.ALLOWED_REPOS }} 
    apply_requirements: []
    checkout_strategy: merge

admin:
  github_team:
    name: atlantis-orchestration
    org: lyft

temporal:
  host: temporalite
  port: 7233
