// Code generated by pegomock. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/controllers/websocket (interfaces: ResponseWriter)

package mocks

import (
	pegomock "github.com/petergtz/pegomock"
	http "net/http"
	"reflect"
	"time"
)

type MockResponseWriter struct {
	fail func(message string, callerSkip ...int)
}

func NewMockResponseWriter(options ...pegomock.Option) *MockResponseWriter {
	mock := &MockResponseWriter{}
	for _, option := range options {
		option.Apply(mock)
	}
	return mock
}

func (mock *MockResponseWriter) SetFailHandler(fh pegomock.FailHandler) { mock.fail = fh }
func (mock *MockResponseWriter) FailHandler() pegomock.FailHandler      { return mock.fail }

func (mock *MockResponseWriter) Header() http.Header {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockResponseWriter().")
	}
	params := []pegomock.Param{}
	result := pegomock.GetGenericMockFrom(mock).Invoke("Header", params, []reflect.Type{reflect.TypeOf((*http.Header)(nil)).Elem()})
	var ret0 http.Header
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(http.Header)
		}
	}
	return ret0
}

func (mock *MockResponseWriter) Write(_param0 []byte) (int, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockResponseWriter().")
	}
	params := []pegomock.Param{_param0}
	result := pegomock.GetGenericMockFrom(mock).Invoke("Write", params, []reflect.Type{reflect.TypeOf((*int)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 int
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(int)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockResponseWriter) WriteHeader(_param0 int) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockResponseWriter().")
	}
	params := []pegomock.Param{_param0}
	pegomock.GetGenericMockFrom(mock).Invoke("WriteHeader", params, []reflect.Type{})
}

func (mock *MockResponseWriter) VerifyWasCalledOnce() *VerifierMockResponseWriter {
	return &VerifierMockResponseWriter{
		mock:                   mock,
		invocationCountMatcher: pegomock.Times(1),
	}
}

func (mock *MockResponseWriter) VerifyWasCalled(invocationCountMatcher pegomock.InvocationCountMatcher) *VerifierMockResponseWriter {
	return &VerifierMockResponseWriter{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
	}
}

func (mock *MockResponseWriter) VerifyWasCalledInOrder(invocationCountMatcher pegomock.InvocationCountMatcher, inOrderContext *pegomock.InOrderContext) *VerifierMockResponseWriter {
	return &VerifierMockResponseWriter{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		inOrderContext:         inOrderContext,
	}
}

func (mock *MockResponseWriter) VerifyWasCalledEventually(invocationCountMatcher pegomock.InvocationCountMatcher, timeout time.Duration) *VerifierMockResponseWriter {
	return &VerifierMockResponseWriter{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		timeout:                timeout,
	}
}

type VerifierMockResponseWriter struct {
	mock                   *MockResponseWriter
	invocationCountMatcher pegomock.InvocationCountMatcher
	inOrderContext         *pegomock.InOrderContext
	timeout                time.Duration
}

func (verifier *VerifierMockResponseWriter) Header() *MockResponseWriter_Header_OngoingVerification {
	params := []pegomock.Param{}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "Header", params, verifier.timeout)
	return &MockResponseWriter_Header_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockResponseWriter_Header_OngoingVerification struct {
	mock              *MockResponseWriter
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockResponseWriter_Header_OngoingVerification) GetCapturedArguments() {
}

func (c *MockResponseWriter_Header_OngoingVerification) GetAllCapturedArguments() {
}

func (verifier *VerifierMockResponseWriter) Write(_param0 []byte) *MockResponseWriter_Write_OngoingVerification {
	params := []pegomock.Param{_param0}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "Write", params, verifier.timeout)
	return &MockResponseWriter_Write_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockResponseWriter_Write_OngoingVerification struct {
	mock              *MockResponseWriter
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockResponseWriter_Write_OngoingVerification) GetCapturedArguments() []byte {
	_param0 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1]
}

func (c *MockResponseWriter_Write_OngoingVerification) GetAllCapturedArguments() (_param0 [][]byte) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([][]byte, len(c.methodInvocations))
		for u, param := range params[0] {
			_param0[u] = param.([]byte)
		}
	}
	return
}

func (verifier *VerifierMockResponseWriter) WriteHeader(_param0 int) *MockResponseWriter_WriteHeader_OngoingVerification {
	params := []pegomock.Param{_param0}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "WriteHeader", params, verifier.timeout)
	return &MockResponseWriter_WriteHeader_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockResponseWriter_WriteHeader_OngoingVerification struct {
	mock              *MockResponseWriter
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockResponseWriter_WriteHeader_OngoingVerification) GetCapturedArguments() int {
	_param0 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1]
}

func (c *MockResponseWriter_WriteHeader_OngoingVerification) GetAllCapturedArguments() (_param0 []int) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]int, len(c.methodInvocations))
		for u, param := range params[0] {
			_param0[u] = param.(int)
		}
	}
	return
}
