// Code generated by pegomock. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/controllers/websocket (interfaces: PartitionRegistry)

package mocks

import (
	pegomock "github.com/petergtz/pegomock"
	"reflect"
	"time"
)

type MockPartitionRegistry struct {
	fail func(message string, callerSkip ...int)
}

func NewMockPartitionRegistry(options ...pegomock.Option) *MockPartitionRegistry {
	mock := &MockPartitionRegistry{}
	for _, option := range options {
		option.Apply(mock)
	}
	return mock
}

func (mock *MockPartitionRegistry) SetFailHandler(fh pegomock.FailHandler) { mock.fail = fh }
func (mock *MockPartitionRegistry) FailHandler() pegomock.FailHandler      { return mock.fail }

func (mock *MockPartitionRegistry) Deregister(_param0 string, _param1 chan string) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockPartitionRegistry().")
	}
	params := []pegomock.Param{_param0, _param1}
	pegomock.GetGenericMockFrom(mock).Invoke("Deregister", params, []reflect.Type{})
}

func (mock *MockPartitionRegistry) IsKeyExists(_param0 string) bool {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockPartitionRegistry().")
	}
	params := []pegomock.Param{_param0}
	result := pegomock.GetGenericMockFrom(mock).Invoke("IsKeyExists", params, []reflect.Type{reflect.TypeOf((*bool)(nil)).Elem()})
	var ret0 bool
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(bool)
		}
	}
	return ret0
}

func (mock *MockPartitionRegistry) Register(_param0 string, _param1 chan string) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockPartitionRegistry().")
	}
	params := []pegomock.Param{_param0, _param1}
	pegomock.GetGenericMockFrom(mock).Invoke("Register", params, []reflect.Type{})
}

func (mock *MockPartitionRegistry) VerifyWasCalledOnce() *VerifierMockPartitionRegistry {
	return &VerifierMockPartitionRegistry{
		mock:                   mock,
		invocationCountMatcher: pegomock.Times(1),
	}
}

func (mock *MockPartitionRegistry) VerifyWasCalled(invocationCountMatcher pegomock.InvocationCountMatcher) *VerifierMockPartitionRegistry {
	return &VerifierMockPartitionRegistry{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
	}
}

func (mock *MockPartitionRegistry) VerifyWasCalledInOrder(invocationCountMatcher pegomock.InvocationCountMatcher, inOrderContext *pegomock.InOrderContext) *VerifierMockPartitionRegistry {
	return &VerifierMockPartitionRegistry{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		inOrderContext:         inOrderContext,
	}
}

func (mock *MockPartitionRegistry) VerifyWasCalledEventually(invocationCountMatcher pegomock.InvocationCountMatcher, timeout time.Duration) *VerifierMockPartitionRegistry {
	return &VerifierMockPartitionRegistry{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		timeout:                timeout,
	}
}

type VerifierMockPartitionRegistry struct {
	mock                   *MockPartitionRegistry
	invocationCountMatcher pegomock.InvocationCountMatcher
	inOrderContext         *pegomock.InOrderContext
	timeout                time.Duration
}

func (verifier *VerifierMockPartitionRegistry) Deregister(_param0 string, _param1 chan string) *MockPartitionRegistry_Deregister_OngoingVerification {
	params := []pegomock.Param{_param0, _param1}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "Deregister", params, verifier.timeout)
	return &MockPartitionRegistry_Deregister_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockPartitionRegistry_Deregister_OngoingVerification struct {
	mock              *MockPartitionRegistry
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockPartitionRegistry_Deregister_OngoingVerification) GetCapturedArguments() (string, chan string) {
	_param0, _param1 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1], _param1[len(_param1)-1]
}

func (c *MockPartitionRegistry_Deregister_OngoingVerification) GetAllCapturedArguments() (_param0 []string, _param1 []chan string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]string, len(c.methodInvocations))
		for u, param := range params[0] {
			_param0[u] = param.(string)
		}
		_param1 = make([]chan string, len(c.methodInvocations))
		for u, param := range params[1] {
			_param1[u] = param.(chan string)
		}
	}
	return
}

func (verifier *VerifierMockPartitionRegistry) IsKeyExists(_param0 string) *MockPartitionRegistry_IsKeyExists_OngoingVerification {
	params := []pegomock.Param{_param0}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "IsKeyExists", params, verifier.timeout)
	return &MockPartitionRegistry_IsKeyExists_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockPartitionRegistry_IsKeyExists_OngoingVerification struct {
	mock              *MockPartitionRegistry
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockPartitionRegistry_IsKeyExists_OngoingVerification) GetCapturedArguments() string {
	_param0 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1]
}

func (c *MockPartitionRegistry_IsKeyExists_OngoingVerification) GetAllCapturedArguments() (_param0 []string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]string, len(c.methodInvocations))
		for u, param := range params[0] {
			_param0[u] = param.(string)
		}
	}
	return
}

func (verifier *VerifierMockPartitionRegistry) Register(_param0 string, _param1 chan string) *MockPartitionRegistry_Register_OngoingVerification {
	params := []pegomock.Param{_param0, _param1}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "Register", params, verifier.timeout)
	return &MockPartitionRegistry_Register_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockPartitionRegistry_Register_OngoingVerification struct {
	mock              *MockPartitionRegistry
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockPartitionRegistry_Register_OngoingVerification) GetCapturedArguments() (string, chan string) {
	_param0, _param1 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1], _param1[len(_param1)-1]
}

func (c *MockPartitionRegistry_Register_OngoingVerification) GetAllCapturedArguments() (_param0 []string, _param1 []chan string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]string, len(c.methodInvocations))
		for u, param := range params[0] {
			_param0[u] = param.(string)
		}
		_param1 = make([]chan string, len(c.methodInvocations))
		for u, param := range params[1] {
			_param1[u] = param.(chan string)
		}
	}
	return
}
