// Code generated by pegomock. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/controllers/websocket (interfaces: StorageBackendReader)

package mocks

import (
	pegomock "github.com/petergtz/pegomock"
	io "io"
	"reflect"
	"time"
)

type MockStorageBackendReader struct {
	fail func(message string, callerSkip ...int)
}

func NewMockStorageBackendReader(options ...pegomock.Option) *MockStorageBackendReader {
	mock := &MockStorageBackendReader{}
	for _, option := range options {
		option.Apply(mock)
	}
	return mock
}

func (mock *MockStorageBackendReader) SetFailHandler(fh pegomock.FailHandler) { mock.fail = fh }
func (mock *MockStorageBackendReader) FailHandler() pegomock.FailHandler      { return mock.fail }

func (mock *MockStorageBackendReader) IsKeyExists(_param0 string) bool {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockStorageBackendReader().")
	}
	params := []pegomock.Param{_param0}
	result := pegomock.GetGenericMockFrom(mock).Invoke("IsKeyExists", params, []reflect.Type{reflect.TypeOf((*bool)(nil)).Elem()})
	var ret0 bool
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(bool)
		}
	}
	return ret0
}

func (mock *MockStorageBackendReader) Read(_param0 string) io.ReadCloser {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockStorageBackendReader().")
	}
	params := []pegomock.Param{_param0}
	result := pegomock.GetGenericMockFrom(mock).Invoke("Read", params, []reflect.Type{reflect.TypeOf((*io.ReadCloser)(nil)).Elem()})
	var ret0 io.ReadCloser
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(io.ReadCloser)
		}
	}
	return ret0
}

func (mock *MockStorageBackendReader) VerifyWasCalledOnce() *VerifierMockStorageBackendReader {
	return &VerifierMockStorageBackendReader{
		mock:                   mock,
		invocationCountMatcher: pegomock.Times(1),
	}
}

func (mock *MockStorageBackendReader) VerifyWasCalled(invocationCountMatcher pegomock.InvocationCountMatcher) *VerifierMockStorageBackendReader {
	return &VerifierMockStorageBackendReader{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
	}
}

func (mock *MockStorageBackendReader) VerifyWasCalledInOrder(invocationCountMatcher pegomock.InvocationCountMatcher, inOrderContext *pegomock.InOrderContext) *VerifierMockStorageBackendReader {
	return &VerifierMockStorageBackendReader{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		inOrderContext:         inOrderContext,
	}
}

func (mock *MockStorageBackendReader) VerifyWasCalledEventually(invocationCountMatcher pegomock.InvocationCountMatcher, timeout time.Duration) *VerifierMockStorageBackendReader {
	return &VerifierMockStorageBackendReader{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		timeout:                timeout,
	}
}

type VerifierMockStorageBackendReader struct {
	mock                   *MockStorageBackendReader
	invocationCountMatcher pegomock.InvocationCountMatcher
	inOrderContext         *pegomock.InOrderContext
	timeout                time.Duration
}

func (verifier *VerifierMockStorageBackendReader) IsKeyExists(_param0 string) *MockStorageBackendReader_IsKeyExists_OngoingVerification {
	params := []pegomock.Param{_param0}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "IsKeyExists", params, verifier.timeout)
	return &MockStorageBackendReader_IsKeyExists_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockStorageBackendReader_IsKeyExists_OngoingVerification struct {
	mock              *MockStorageBackendReader
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockStorageBackendReader_IsKeyExists_OngoingVerification) GetCapturedArguments() string {
	_param0 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1]
}

func (c *MockStorageBackendReader_IsKeyExists_OngoingVerification) GetAllCapturedArguments() (_param0 []string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]string, len(c.methodInvocations))
		for u, param := range params[0] {
			_param0[u] = param.(string)
		}
	}
	return
}

func (verifier *VerifierMockStorageBackendReader) Read(_param0 string) *MockStorageBackendReader_Read_OngoingVerification {
	params := []pegomock.Param{_param0}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "Read", params, verifier.timeout)
	return &MockStorageBackendReader_Read_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockStorageBackendReader_Read_OngoingVerification struct {
	mock              *MockStorageBackendReader
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockStorageBackendReader_Read_OngoingVerification) GetCapturedArguments() string {
	_param0 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1]
}

func (c *MockStorageBackendReader_Read_OngoingVerification) GetAllCapturedArguments() (_param0 []string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]string, len(c.methodInvocations))
		for u, param := range params[0] {
			_param0[u] = param.(string)
		}
	}
	return
}
