// Code generated by pegomock. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/controllers/websocket (interfaces: Reader)

package mocks

import (
	pegomock "github.com/petergtz/pegomock"
	io "io"
	"reflect"
	"time"
)

type MockReader struct {
	fail func(message string, callerSkip ...int)
}

func NewMockReader(options ...pegomock.Option) *MockReader {
	mock := &MockReader{}
	for _, option := range options {
		option.Apply(mock)
	}
	return mock
}

func (mock *MockReader) SetFailHandler(fh pegomock.FailHandler) { mock.fail = fh }
func (mock *MockReader) FailHandler() pegomock.FailHandler      { return mock.fail }

func (mock *MockReader) IsKeyExists(_param0 string) bool {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockReader().")
	}
	params := []pegomock.Param{_param0}
	result := pegomock.GetGenericMockFrom(mock).Invoke("IsKeyExists", params, []reflect.Type{reflect.TypeOf((*bool)(nil)).Elem()})
	var ret0 bool
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(bool)
		}
	}
	return ret0
}

func (mock *MockReader) Read(_param0 string) io.ReadCloser {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockReader().")
	}
	params := []pegomock.Param{_param0}
	result := pegomock.GetGenericMockFrom(mock).Invoke("Read", params, []reflect.Type{reflect.TypeOf((*io.ReadCloser)(nil)).Elem()})
	var ret0 io.ReadCloser
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(io.ReadCloser)
		}
	}
	return ret0
}

func (mock *MockReader) VerifyWasCalledOnce() *VerifierMockReader {
	return &VerifierMockReader{
		mock:                   mock,
		invocationCountMatcher: pegomock.Times(1),
	}
}

func (mock *MockReader) VerifyWasCalled(invocationCountMatcher pegomock.InvocationCountMatcher) *VerifierMockReader {
	return &VerifierMockReader{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
	}
}

func (mock *MockReader) VerifyWasCalledInOrder(invocationCountMatcher pegomock.InvocationCountMatcher, inOrderContext *pegomock.InOrderContext) *VerifierMockReader {
	return &VerifierMockReader{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		inOrderContext:         inOrderContext,
	}
}

func (mock *MockReader) VerifyWasCalledEventually(invocationCountMatcher pegomock.InvocationCountMatcher, timeout time.Duration) *VerifierMockReader {
	return &VerifierMockReader{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		timeout:                timeout,
	}
}

type VerifierMockReader struct {
	mock                   *MockReader
	invocationCountMatcher pegomock.InvocationCountMatcher
	inOrderContext         *pegomock.InOrderContext
	timeout                time.Duration
}

func (verifier *VerifierMockReader) IsKeyExists(_param0 string) *MockReader_IsKeyExists_OngoingVerification {
	params := []pegomock.Param{_param0}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "IsKeyExists", params, verifier.timeout)
	return &MockReader_IsKeyExists_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockReader_IsKeyExists_OngoingVerification struct {
	mock              *MockReader
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockReader_IsKeyExists_OngoingVerification) GetCapturedArguments() string {
	_param0 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1]
}

func (c *MockReader_IsKeyExists_OngoingVerification) GetAllCapturedArguments() (_param0 []string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]string, len(c.methodInvocations))
		for u, param := range params[0] {
			_param0[u] = param.(string)
		}
	}
	return
}

func (verifier *VerifierMockReader) Read(_param0 string) *MockReader_Read_OngoingVerification {
	params := []pegomock.Param{_param0}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "Read", params, verifier.timeout)
	return &MockReader_Read_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockReader_Read_OngoingVerification struct {
	mock              *MockReader
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockReader_Read_OngoingVerification) GetCapturedArguments() string {
	_param0 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1]
}

func (c *MockReader_Read_OngoingVerification) GetAllCapturedArguments() (_param0 []string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]string, len(c.methodInvocations))
		for u, param := range params[0] {
			_param0[u] = param.(string)
		}
	}
	return
}
