// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"

	"github.com/runatlantis/atlantis/server/legacy/events/command"
)

func AnyPtrToEventsCommentCommand() *command.Comment {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*command.Comment))(nil)).Elem()))
	var nullValue *command.Comment
	return nullValue
}

func EqPtrToEventsCommentCommand(value *command.Comment) *command.Comment {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *command.Comment
	return nullValue
}
