// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"

	"github.com/petergtz/pegomock"

	command "github.com/runatlantis/atlantis/server/legacy/events/command"
)

func AnyPtrToCommandComment() *command.Comment {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*command.Comment))(nil)).Elem()))
	var nullValue *command.Comment
	return nullValue
}

func EqPtrToCommandComment(value *command.Comment) *command.Comment {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *command.Comment
	return nullValue
}

func NotEqPtrToCommandComment(value *command.Comment) *command.Comment {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue *command.Comment
	return nullValue
}

func PtrToCommandCommentThat(matcher pegomock.ArgumentMatcher) *command.Comment {
	pegomock.RegisterMatcher(matcher)
	var nullValue *command.Comment
	return nullValue
}
