// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	exec "os/exec"
	"reflect"

	"github.com/petergtz/pegomock"
)

func AnyPtrToExecCmd() *exec.Cmd {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*exec.Cmd))(nil)).Elem()))
	var nullValue *exec.Cmd
	return nullValue
}

func EqPtrToExecCmd(value *exec.Cmd) *exec.Cmd {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *exec.Cmd
	return nullValue
}
