// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"

	"github.com/petergtz/pegomock"
	"github.com/runatlantis/atlantis/server/events/command/project"
)

func AnyModelsProjectCommandContext() project.Context {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(project.Context))(nil)).Elem()))
	var nullValue project.Context
	return nullValue
}

func EqModelsProjectCommandContext(value project.Context) project.Context {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue project.Context
	return nullValue
}

func NotEqModelsProjectCommandContext(value project.Context) project.Context {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue project.Context
	return nullValue
}

func ModelsProjectCommandContextThat(matcher pegomock.ArgumentMatcher) project.Context {
	pegomock.RegisterMatcher(matcher)
	var nullValue project.Context
	return nullValue
}
