// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"

	models "github.com/runatlantis/atlantis/server/events/models"
)

func AnyModelsJobContext() models.JobContext {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(models.JobContext))(nil)).Elem()))
	var nullValue models.JobContext
	return nullValue
}

func EqModelsJobContext(value models.JobContext) models.JobContext {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue models.JobContext
	return nullValue
}

func NotEqModelsJobContext(value models.JobContext) models.JobContext {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue models.JobContext
	return nullValue
}

func ModelsJobContextThat(matcher pegomock.ArgumentMatcher) models.JobContext {
	pegomock.RegisterMatcher(matcher)
	var nullValue models.JobContext
	return nullValue
}
