// Code generated by pegomock. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/neptune/gateway/event/source (interfaces: FileFetcher)

package mocks

import (
	context "context"
	pegomock "github.com/petergtz/pegomock"
	models "github.com/runatlantis/atlantis/server/events/models"
	"reflect"
	"time"
)

type MockFileFetcher struct {
	fail func(message string, callerSkip ...int)
}

func NewMockFileFetcher(options ...pegomock.Option) *MockFileFetcher {
	mock := &MockFileFetcher{}
	for _, option := range options {
		option.Apply(mock)
	}
	return mock
}

func (mock *MockFileFetcher) SetFailHandler(fh pegomock.FailHandler) { mock.fail = fh }
func (mock *MockFileFetcher) FailHandler() pegomock.FailHandler      { return mock.fail }

func (mock *MockFileFetcher) GetModifiedFilesFromCommit(ctx context.Context, repo models.Repo, sha string, installationToken int64) ([]string, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockFileFetcher().")
	}
	params := []pegomock.Param{ctx, repo, sha, installationToken}
	result := pegomock.GetGenericMockFrom(mock).Invoke("GetModifiedFilesFromCommit", params, []reflect.Type{reflect.TypeOf((*[]string)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 []string
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].([]string)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockFileFetcher) VerifyWasCalledOnce() *VerifierMockFileFetcher {
	return &VerifierMockFileFetcher{
		mock:                   mock,
		invocationCountMatcher: pegomock.Times(1),
	}
}

func (mock *MockFileFetcher) VerifyWasCalled(invocationCountMatcher pegomock.InvocationCountMatcher) *VerifierMockFileFetcher {
	return &VerifierMockFileFetcher{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
	}
}

func (mock *MockFileFetcher) VerifyWasCalledInOrder(invocationCountMatcher pegomock.InvocationCountMatcher, inOrderContext *pegomock.InOrderContext) *VerifierMockFileFetcher {
	return &VerifierMockFileFetcher{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		inOrderContext:         inOrderContext,
	}
}

func (mock *MockFileFetcher) VerifyWasCalledEventually(invocationCountMatcher pegomock.InvocationCountMatcher, timeout time.Duration) *VerifierMockFileFetcher {
	return &VerifierMockFileFetcher{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		timeout:                timeout,
	}
}

type VerifierMockFileFetcher struct {
	mock                   *MockFileFetcher
	invocationCountMatcher pegomock.InvocationCountMatcher
	inOrderContext         *pegomock.InOrderContext
	timeout                time.Duration
}

func (verifier *VerifierMockFileFetcher) GetModifiedFilesFromCommit(ctx context.Context, repo models.Repo, sha string, installationToken int64) *MockFileFetcher_GetModifiedFilesFromCommit_OngoingVerification {
	params := []pegomock.Param{ctx, repo, sha, installationToken}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "GetModifiedFilesFromCommit", params, verifier.timeout)
	return &MockFileFetcher_GetModifiedFilesFromCommit_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockFileFetcher_GetModifiedFilesFromCommit_OngoingVerification struct {
	mock              *MockFileFetcher
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockFileFetcher_GetModifiedFilesFromCommit_OngoingVerification) GetCapturedArguments() (context.Context, models.Repo, string, int64) {
	ctx, repo, sha, installationToken := c.GetAllCapturedArguments()
	return ctx[len(ctx)-1], repo[len(repo)-1], sha[len(sha)-1], installationToken[len(installationToken)-1]
}

func (c *MockFileFetcher_GetModifiedFilesFromCommit_OngoingVerification) GetAllCapturedArguments() (_param0 []context.Context, _param1 []models.Repo, _param2 []string, _param3 []int64) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]context.Context, len(c.methodInvocations))
		for u, param := range params[0] {
			_param0[u] = param.(context.Context)
		}
		_param1 = make([]models.Repo, len(c.methodInvocations))
		for u, param := range params[1] {
			_param1[u] = param.(models.Repo)
		}
		_param2 = make([]string, len(c.methodInvocations))
		for u, param := range params[2] {
			_param2[u] = param.(string)
		}
		_param3 = make([]int64, len(c.methodInvocations))
		for u, param := range params[3] {
			_param3[u] = param.(int64)
		}
	}
	return
}
