// Code generated by pegomock. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/neptune/gateway/event/source (interfaces: ProjectFinder)

package mocks

import (
	pegomock "github.com/petergtz/pegomock"
	valid "github.com/runatlantis/atlantis/server/core/config/valid"
	models "github.com/runatlantis/atlantis/server/events/models"
	"reflect"
	"time"
)

type MockProjectFinder struct {
	fail func(message string, callerSkip ...int)
}

func NewMockProjectFinder(options ...pegomock.Option) *MockProjectFinder {
	mock := &MockProjectFinder{}
	for _, option := range options {
		option.Apply(mock)
	}
	return mock
}

func (mock *MockProjectFinder) SetFailHandler(fh pegomock.FailHandler) { mock.fail = fh }
func (mock *MockProjectFinder) FailHandler() pegomock.FailHandler      { return mock.fail }

func (mock *MockProjectFinder) DetermineProjects(modifiedFiles []string, repoFullName string, absRepoDir string, autoplanFileList string) []models.Project {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockProjectFinder().")
	}
	params := []pegomock.Param{modifiedFiles, repoFullName, absRepoDir, autoplanFileList}
	result := pegomock.GetGenericMockFrom(mock).Invoke("DetermineProjects", params, []reflect.Type{reflect.TypeOf((*[]models.Project)(nil)).Elem()})
	var ret0 []models.Project
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].([]models.Project)
		}
	}
	return ret0
}

func (mock *MockProjectFinder) DetermineProjectsViaConfig(modifiedFiles []string, config valid.RepoCfg, absRepoDir string) ([]valid.Project, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockProjectFinder().")
	}
	params := []pegomock.Param{modifiedFiles, config, absRepoDir}
	result := pegomock.GetGenericMockFrom(mock).Invoke("DetermineProjectsViaConfig", params, []reflect.Type{reflect.TypeOf((*[]valid.Project)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 []valid.Project
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].([]valid.Project)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockProjectFinder) VerifyWasCalledOnce() *VerifierMockProjectFinder {
	return &VerifierMockProjectFinder{
		mock:                   mock,
		invocationCountMatcher: pegomock.Times(1),
	}
}

func (mock *MockProjectFinder) VerifyWasCalled(invocationCountMatcher pegomock.InvocationCountMatcher) *VerifierMockProjectFinder {
	return &VerifierMockProjectFinder{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
	}
}

func (mock *MockProjectFinder) VerifyWasCalledInOrder(invocationCountMatcher pegomock.InvocationCountMatcher, inOrderContext *pegomock.InOrderContext) *VerifierMockProjectFinder {
	return &VerifierMockProjectFinder{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		inOrderContext:         inOrderContext,
	}
}

func (mock *MockProjectFinder) VerifyWasCalledEventually(invocationCountMatcher pegomock.InvocationCountMatcher, timeout time.Duration) *VerifierMockProjectFinder {
	return &VerifierMockProjectFinder{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		timeout:                timeout,
	}
}

type VerifierMockProjectFinder struct {
	mock                   *MockProjectFinder
	invocationCountMatcher pegomock.InvocationCountMatcher
	inOrderContext         *pegomock.InOrderContext
	timeout                time.Duration
}

func (verifier *VerifierMockProjectFinder) DetermineProjects(modifiedFiles []string, repoFullName string, absRepoDir string, autoplanFileList string) *MockProjectFinder_DetermineProjects_OngoingVerification {
	params := []pegomock.Param{modifiedFiles, repoFullName, absRepoDir, autoplanFileList}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "DetermineProjects", params, verifier.timeout)
	return &MockProjectFinder_DetermineProjects_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockProjectFinder_DetermineProjects_OngoingVerification struct {
	mock              *MockProjectFinder
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockProjectFinder_DetermineProjects_OngoingVerification) GetCapturedArguments() ([]string, string, string, string) {
	modifiedFiles, repoFullName, absRepoDir, autoplanFileList := c.GetAllCapturedArguments()
	return modifiedFiles[len(modifiedFiles)-1], repoFullName[len(repoFullName)-1], absRepoDir[len(absRepoDir)-1], autoplanFileList[len(autoplanFileList)-1]
}

func (c *MockProjectFinder_DetermineProjects_OngoingVerification) GetAllCapturedArguments() (_param0 [][]string, _param1 []string, _param2 []string, _param3 []string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([][]string, len(c.methodInvocations))
		for u, param := range params[0] {
			_param0[u] = param.([]string)
		}
		_param1 = make([]string, len(c.methodInvocations))
		for u, param := range params[1] {
			_param1[u] = param.(string)
		}
		_param2 = make([]string, len(c.methodInvocations))
		for u, param := range params[2] {
			_param2[u] = param.(string)
		}
		_param3 = make([]string, len(c.methodInvocations))
		for u, param := range params[3] {
			_param3[u] = param.(string)
		}
	}
	return
}

func (verifier *VerifierMockProjectFinder) DetermineProjectsViaConfig(modifiedFiles []string, config valid.RepoCfg, absRepoDir string) *MockProjectFinder_DetermineProjectsViaConfig_OngoingVerification {
	params := []pegomock.Param{modifiedFiles, config, absRepoDir}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "DetermineProjectsViaConfig", params, verifier.timeout)
	return &MockProjectFinder_DetermineProjectsViaConfig_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockProjectFinder_DetermineProjectsViaConfig_OngoingVerification struct {
	mock              *MockProjectFinder
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockProjectFinder_DetermineProjectsViaConfig_OngoingVerification) GetCapturedArguments() ([]string, valid.RepoCfg, string) {
	modifiedFiles, config, absRepoDir := c.GetAllCapturedArguments()
	return modifiedFiles[len(modifiedFiles)-1], config[len(config)-1], absRepoDir[len(absRepoDir)-1]
}

func (c *MockProjectFinder_DetermineProjectsViaConfig_OngoingVerification) GetAllCapturedArguments() (_param0 [][]string, _param1 []valid.RepoCfg, _param2 []string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([][]string, len(c.methodInvocations))
		for u, param := range params[0] {
			_param0[u] = param.([]string)
		}
		_param1 = make([]valid.RepoCfg, len(c.methodInvocations))
		for u, param := range params[1] {
			_param1[u] = param.(valid.RepoCfg)
		}
		_param2 = make([]string, len(c.methodInvocations))
		for u, param := range params[2] {
			_param2[u] = param.(string)
		}
	}
	return
}
