// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"

	valid "github.com/runatlantis/atlantis/server/core/config/valid"
)

func AnyPtrToValidPreWorkflowHook() *valid.PreWorkflowHook {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*valid.PreWorkflowHook))(nil)).Elem()))
	var nullValue *valid.PreWorkflowHook
	return nullValue
}

func EqPtrToValidPreWorkflowHook(value *valid.PreWorkflowHook) *valid.PreWorkflowHook {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *valid.PreWorkflowHook
	return nullValue
}

func NotEqPtrToValidPreWorkflowHook(value *valid.PreWorkflowHook) *valid.PreWorkflowHook {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue *valid.PreWorkflowHook
	return nullValue
}

func PtrToValidPreWorkflowHookThat(matcher pegomock.ArgumentMatcher) *valid.PreWorkflowHook {
	pegomock.RegisterMatcher(matcher)
	var nullValue *valid.PreWorkflowHook
	return nullValue
}
