// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"

	"github.com/petergtz/pegomock"
	"github.com/runatlantis/atlantis/server/events/command/project"
)

func AnyModelsProjectResult() project.Result {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(project.Result))(nil)).Elem()))
	var nullValue project.Result
	return nullValue
}

func EqModelsProjectResult(value project.Result) project.Result {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue project.Result
	return nullValue
}

func NotEqModelsProjectResult(value project.Result) project.Result {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue project.Result
	return nullValue
}

func ModelsProjectResultThat(matcher pegomock.ArgumentMatcher) project.Result {
	pegomock.RegisterMatcher(matcher)
	var nullValue project.Result
	return nullValue
}
