// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"

	models "github.com/runatlantis/atlantis/server/events/models"
)

func AnyModelsVcsStatus() models.VcsStatus {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(models.VcsStatus))(nil)).Elem()))
	var nullValue models.VcsStatus
	return nullValue
}

func EqModelsVcsStatus(value models.VcsStatus) models.VcsStatus {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue models.VcsStatus
	return nullValue
}

func NotEqModelsVcsStatus(value models.VcsStatus) models.VcsStatus {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue models.VcsStatus
	return nullValue
}

func ModelsVcsStatusThat(matcher pegomock.ArgumentMatcher) models.VcsStatus {
	pegomock.RegisterMatcher(matcher)
	var nullValue models.VcsStatus
	return nullValue
}
