// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"

	models "github.com/runatlantis/atlantis/server/events/models"
)

func AnyPtrToEventsCommandContext() *models.CommandContext {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*models.CommandContext))(nil)).Elem()))
	var nullValue *models.CommandContext
	return nullValue
}

func EqPtrToEventsCommandContext(value *models.CommandContext) *models.CommandContext {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *models.CommandContext
	return nullValue
}

func NotEqPtrToEventsCommandContext(value *models.CommandContext) *models.CommandContext {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue *models.CommandContext
	return nullValue
}

func PtrToEventsCommandContextThat(matcher pegomock.ArgumentMatcher) *models.CommandContext {
	pegomock.RegisterMatcher(matcher)
	var nullValue *models.CommandContext
	return nullValue
}
