// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	models "github.com/runatlantis/atlantis/server/events/models"
)

func AnyPtrToModelsCommandContext() *CommandContext {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*CommandContext))(nil)).Elem()))
	var nullValue *CommandContext
	return nullValue
}

func EqPtrToModelsCommandContext(value *CommandContext) *CommandContext {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *CommandContext
	return nullValue
}
