// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	parsers "github.com/runatlantis/atlantis/server/events/parsers"
	"reflect"
)

func AnyPtrToEventsCommentCommand() *parsers.CommentCommand {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*parsers.CommentCommand))(nil)).Elem()))
	var nullValue *parsers.CommentCommand
	return nullValue
}

func EqPtrToEventsCommentCommand(value *parsers.CommentCommand) *parsers.CommentCommand {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *parsers.CommentCommand
	return nullValue
}
