// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"

	models "github.com/runatlantis/atlantis/server/events/models"
)

func AnySliceOfModelsProject() []models.Project {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*([]models.Project))(nil)).Elem()))
	var nullValue []models.Project
	return nullValue
}

func EqSliceOfModelsProject(value []models.Project) []models.Project {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue []models.Project
	return nullValue
}

func NotEqSliceOfModelsProject(value []models.Project) []models.Project {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue []models.Project
	return nullValue
}

func SliceOfModelsProjectThat(matcher pegomock.ArgumentMatcher) []models.Project {
	pegomock.RegisterMatcher(matcher)
	var nullValue []models.Project
	return nullValue
}
