// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"

	valid "github.com/runatlantis/atlantis/server/events/yaml/valid"
)

func AnySliceOfValidProject() []valid.Project {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*([]valid.Project))(nil)).Elem()))
	var nullValue []valid.Project
	return nullValue
}

func EqSliceOfValidProject(value []valid.Project) []valid.Project {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue []valid.Project
	return nullValue
}

func NotEqSliceOfValidProject(value []valid.Project) []valid.Project {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue []valid.Project
	return nullValue
}

func SliceOfValidProjectThat(matcher pegomock.ArgumentMatcher) []valid.Project {
	pegomock.RegisterMatcher(matcher)
	var nullValue []valid.Project
	return nullValue
}
