// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"

	valid "github.com/runatlantis/atlantis/server/events/yaml/valid"
)

func AnyValidRepoCfg() valid.RepoCfg {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(valid.RepoCfg))(nil)).Elem()))
	var nullValue valid.RepoCfg
	return nullValue
}

func EqValidRepoCfg(value valid.RepoCfg) valid.RepoCfg {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue valid.RepoCfg
	return nullValue
}

func NotEqValidRepoCfg(value valid.RepoCfg) valid.RepoCfg {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue valid.RepoCfg
	return nullValue
}

func ValidRepoCfgThat(matcher pegomock.ArgumentMatcher) valid.RepoCfg {
	pegomock.RegisterMatcher(matcher)
	var nullValue valid.RepoCfg
	return nullValue
}
