// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	"reflect"

	valid "github.com/runatlantis/atlantis/server/events/yaml/valid"
)

func AnyValidGlobalCfg() valid.GlobalCfg {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(valid.GlobalCfg))(nil)).Elem()))
	var nullValue valid.GlobalCfg
	return nullValue
}

func EqValidGlobalCfg(value valid.GlobalCfg) valid.GlobalCfg {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue valid.GlobalCfg
	return nullValue
}

func NotEqValidGlobalCfg(value valid.GlobalCfg) valid.GlobalCfg {
	pegomock.RegisterMatcher(&pegomock.NotEqMatcher{Value: value})
	var nullValue valid.GlobalCfg
	return nullValue
}

func ValidGlobalCfgThat(matcher pegomock.ArgumentMatcher) valid.GlobalCfg {
	pegomock.RegisterMatcher(matcher)
	var nullValue valid.GlobalCfg
	return nullValue
}
