// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	terraform "github.com/runatlantis/atlantis/server/core/terraform"
)

func AnyRecvChanOfTerraformLine() <-chan terraform.Line {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(<-chan terraform.Line))(nil)).Elem()))
	var nullValue <-chan terraform.Line
	return nullValue
}

func EqRecvChanOfTerraformLine(value <-chan terraform.Line) <-chan terraform.Line {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue <-chan terraform.Line
	return nullValue
}
