// Code generated by pegomock. DO NOT EDIT.
// Source: github.com/runatlantis/atlantis/server/neptune/gateway/event/preworkflow (interfaces: HooksRunner)

package mocks

import (
	pegomock "github.com/petergtz/pegomock"
	models "github.com/runatlantis/atlantis/server/events/models"
	"reflect"
	"time"
)

type MockHooksRunner struct {
	fail func(message string, callerSkip ...int)
}

func NewMockHooksRunner(options ...pegomock.Option) *MockHooksRunner {
	mock := &MockHooksRunner{}
	for _, option := range options {
		option.Apply(mock)
	}
	return mock
}

func (mock *MockHooksRunner) SetFailHandler(fh pegomock.FailHandler) { mock.fail = fh }
func (mock *MockHooksRunner) FailHandler() pegomock.FailHandler      { return mock.fail }

func (mock *MockHooksRunner) Run(repo models.Repo, sha string) (string, error) {
	if mock == nil {
		panic("mock must not be nil. Use myMock := NewMockHooksRunner().")
	}
	params := []pegomock.Param{repo, sha}
	result := pegomock.GetGenericMockFrom(mock).Invoke("Run", params, []reflect.Type{reflect.TypeOf((*string)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 string
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(string)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockHooksRunner) VerifyWasCalledOnce() *VerifierMockHooksRunner {
	return &VerifierMockHooksRunner{
		mock:                   mock,
		invocationCountMatcher: pegomock.Times(1),
	}
}

func (mock *MockHooksRunner) VerifyWasCalled(invocationCountMatcher pegomock.InvocationCountMatcher) *VerifierMockHooksRunner {
	return &VerifierMockHooksRunner{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
	}
}

func (mock *MockHooksRunner) VerifyWasCalledInOrder(invocationCountMatcher pegomock.InvocationCountMatcher, inOrderContext *pegomock.InOrderContext) *VerifierMockHooksRunner {
	return &VerifierMockHooksRunner{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		inOrderContext:         inOrderContext,
	}
}

func (mock *MockHooksRunner) VerifyWasCalledEventually(invocationCountMatcher pegomock.InvocationCountMatcher, timeout time.Duration) *VerifierMockHooksRunner {
	return &VerifierMockHooksRunner{
		mock:                   mock,
		invocationCountMatcher: invocationCountMatcher,
		timeout:                timeout,
	}
}

type VerifierMockHooksRunner struct {
	mock                   *MockHooksRunner
	invocationCountMatcher pegomock.InvocationCountMatcher
	inOrderContext         *pegomock.InOrderContext
	timeout                time.Duration
}

func (verifier *VerifierMockHooksRunner) Run(repo models.Repo, sha string) *MockHooksRunner_Run_OngoingVerification {
	params := []pegomock.Param{repo, sha}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "Run", params, verifier.timeout)
	return &MockHooksRunner_Run_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type MockHooksRunner_Run_OngoingVerification struct {
	mock              *MockHooksRunner
	methodInvocations []pegomock.MethodInvocation
}

func (c *MockHooksRunner_Run_OngoingVerification) GetCapturedArguments() (models.Repo, string) {
	repo, sha := c.GetAllCapturedArguments()
	return repo[len(repo)-1], sha[len(sha)-1]
}

func (c *MockHooksRunner_Run_OngoingVerification) GetAllCapturedArguments() (_param0 []models.Repo, _param1 []string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]models.Repo, len(c.methodInvocations))
		for u, param := range params[0] {
			_param0[u] = param.(models.Repo)
		}
		_param1 = make([]string, len(c.methodInvocations))
		for u, param := range params[1] {
			_param1[u] = param.(string)
		}
	}
	return
}
