name: linter
on: 
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - uses: actions/checkout@v3
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          args: --timeout 3m --verbose --disable revive
          version: v1.56.2
