name: tester
on: [push]
jobs:
  test:
    name: runner / gotest
    runs-on: ubuntu-latest
    env:
      CONFTEST_VERSION: 0.25.0
      TERRAFORM_VERSION: 1.0.5
    steps:
      - name: Terraform Install
        run: |
          cd /tmp && \
          curl -LOks https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
          sudo mkdir -p /usr/local/bin/tf/versions/${TERRAFORM_VERSION} && \
          sudo unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin/tf/versions/${TERRAFORM_VERSION} && \
          sudo rm /usr/local/bin/terraform && \
          sudo ln -s /usr/local/bin/tf/versions/${TERRAFORM_VERSION}/terraform /usr/local/bin/terraform
      - name: Conftest Install
        run: |
          cd /tmp && \
            curl -sSL https://github.com/open-policy-agent/conftest/releases/download/v${CONFTEST_VERSION}/conftest_${CONFTEST_VERSION}_Linux_x86_64.tar.gz \
            | tar vxz \
            && sudo cp conftest /usr/local/bin/conftest${CONFTEST_VERSION} \
            && sudo cp conftest /usr/local/bin/conftest
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - run: make test-all
