name: tester
on: [push]
jobs:
  test:
    name: runner / gotest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - run: make test-all
